FROM openjdk:11-jdk-alpine
EXPOSE 8081
ADD target/Timesheet-spring-boot-core-data-jpa-mvc-REST-1-1.0.war Timesheet-spring-boot-core-data-jpa-mvc-REST-1-1.0.war
ENTRYPOINT ["java","-jar","/Timesheet-spring-boot-core-data-jpa-mvc-REST-1-1.0.war"]